[package]
name = "sp__e_scale_degree"
version = "1.0.0"
edition = "2024"

[dependencies]
sp__s_impossible_operation_error = { path = "../sp__s_impossible_operation_error" }
sp__t_keyboard_friendly_name = { path = "../sp__t_keyboard_friendly_name" }
